### ISSUE TITLE
Lucas Grey is wounded and covered in blood during the Ambrose Island helicopter extract cutscene

### ISSUE THREAD

**Issue by Ocean-Minnow** [glacier-modding/H3-Community-Patches#122]
It seems like they used the wrong version. This should be replaced with his unwounded version. I'm not sure of the TEMP name at the moment, but it displays in the SDK Debug Mod as `Cinematic_LucasGrey_Jacket`.

![image](https://github.com/glacier-modding/H3-Community-Patches/assets/152698454/23b97712-0448-423e-bea5-923d87272cf3)

**Comment by AnthonyFuller** [comment]
> This should be replaced with his appearance in Carpathian Mountains.

This is his appearance in Carpathian Mountains.
