### ISSUE TITLE
Lethal Poison Vial Version 2 Inventory Graphic Identical to Version 1 

### ISSUE THREAD

**Issue by luxmanifestus** [glacier-modding/H3-Community-Patches#126]
The inventory graphic of the second version of the lethal poison vial (larger and taller bottle) is identical to the first version (shorter syringe bottle). This is a gameplay issue in Freelancer when one has both in inventory and the choice between the crafted lethal poison and the collectable tool poison is presented to the player when poisoning a consumable; the two appear identical and cannot be distinguished, making it impossible to save the tool by using the craftable version, without first dropping the tool. This would require adding a graphic asset of the second version for the inventory to the game.

**Comment by luxmanifestus** [comment]
Incidentally, this issue is also present for the various rarities of the scrambler tools, which also appear identically in the inventory menu.

**Comment by Ocean-Minnow** [comment]
While I can say this is definitely an annoyance, it is not a bug, and thus not within the scope of this particular mod.
