### ISSUE TITLE
OOB Props and Flags Not Waving in New York

### ISSUE THREAD

**Issue by dribbleondo** [glacier-modding/H3-Community-Patches#135]
Several props are misplaced outside (bins floating outside the tellers' window, and a chair floating outside on the right-most window), while most of the flags have no Frustrum Distance Units applied, so they never wave unless the player is really close by, which kinda ruins the point really.

These issues are especially noticeable when the player looks outside the window of the tellers' office.

![screenshot_7003](https://github.com/user-attachments/assets/41d73e5d-eeaa-4c96-99a5-d1a35ab839b2)
![screenshot_7002](https://github.com/user-attachments/assets/1867f0cc-71f9-4fd4-88f3-be79e03842c4)
![screenshot_7007](https://github.com/user-attachments/assets/b4dc597c-4049-4c88-bb70-e535d295eb13)
![screenshot_7006](https://github.com/user-attachments/assets/4ecca746-6884-4f79-9542-a37cf3044c3d)
![screenshot_7004](https://github.com/user-attachments/assets/5900ffe0-6c39-45ef-8b92-f53cf043a33e)

Two separate pull requests have been submitted, this is just for the projects board.

**Comment by Ocean-Minnow** [comment]
Fixed by #133 and #134
