### ISSUE TITLE
Freelancer Safehouse wall hangings are "linked"

### ISSUE THREAD

**Issue by Ocean-Minnow** [glacier-modding/H3-Community-Patches#136]
One of the Freelancer safehouse wall hanging slots in the hallway is "linked" to one of the ones in the bedroom. They'll share the same number as each other, in a sense.

- In the safehouse bedroom, change the wall hanging in the corner by the closet, taking note of how far it is from the default when scrolling to the right (e.g.  If the canvas laying on the floor is taken as 0, then the Space Conflict poster is 10)
- Reload the safehouse by exiting to the main menu or going on a mission
- The wall hanging at the end of the hall closest to the living room will have changed to match the bedroom's number (e.g. if the Space Conflict poster (10) was chosen, the hallway will now be the Souvenir Photos of Sapienza, Bangkok, and Paris (also 10))

**Comment by VoodooHillbilly** [comment]
I've made a fix. Paintings are separate now. I haven't run into any problems yet caused by creating new IDs for the bedroom hatch painting slot.
