### ISSUE TITLE
ICA Proximity Micro Taser is Regarded Like a Coin by NPCs

### ISSUE THREAD

**Issue by luxmanifestus** [glacier-modding/H3-Community-Patches#141]
The ICA Proximity Micro Taser is not only visible to npcs, it attracts their attention like a coin, luring them and enticing them to pick it up. This makes the micro proxy taser an over-powered inconspicuous kill trap, granting the player an near guaranteed SA kill with no risk at all (as it is not illegal to hold or place it), which spoils the difficulty balance and challenge of the game.
![Screenshot 2024-07-21 104053](https://github.com/user-attachments/assets/631703c3-474a-44d0-a35b-798bec12777f)

**Comment by dribbleondo** [comment]
This was actually officially fixed in this patch (season of the drop 2024).

**Comment by Ocean-Minnow** [comment]
As dribbleondo said, officially fixed in September 2024 (two months after this issue was created)
