### ISSUE TITLE
Civilian in Berlin has invisible torso body part

### ISSUE THREAD

**Issue by JojjeE** [glacier-modding/H3-Community-Patches#16]
Putting this here so we don't forget, cannot check outfit or variation right now.

Male civilian by the projection bar.

**Comment by Ocean-Minnow** [comment]
NPC name is Emanuel Knepp

Outfit is `Edgy_Civilian_Raver_M`

Variation 16

TEMP `000DA1E255A3DA4C` or `[assembly:/_pro/characters/templates/fox/char_fox_civilians.template?/outfit_fox_civilian_raver_m_actor_v16.entitytemplate].pc_entitytemplate`

**Comment by JojjeE** [comment]
This is a funny oversight bug because the `TEMP` you've posted does have a top body part which is present in m_aBodyParts.
It's called `Mesh_tracksuit_01` and points to an `m_pMeshResource` which is `00954F2A467328E9.PRIM`. This exists in chunk0patch3, chunk2patch2 and chunk4.

It is in the deletion lists of chunk0patch4, chunk2patch3 and chunk4patch2. It is deleted from all chunks where it exists. Good stuff
