### ISSUE TITLE
Freelancer Safehouse Newspaper Cover in the Office looks VERY fake

### ISSUE THREAD

**Issue by dribbleondo** [glacier-modding/H3-Community-Patches#167]
As described in the title, the newspaper in the Freelancer office has a very fake looking cover for the newspaper on the desk. This has annoyed me since I saw it and I've been meaning to fix it.
### **Before:**
![screenshot_7795](https://github.com/user-attachments/assets/d9bd9923-c7b7-4b92-9345-6f06a8066ecc)
### **After:**
![screenshot_7793](https://github.com/user-attachments/assets/0ed81363-faeb-4c69-b036-8ccc834294a4)

#166 should fix this, this is just for the board.

**Comment by Ocean-Minnow** [comment]
Reopening this issue since #166 was merged before it should have been. From what I could see, the majority of people who commented about it disagreed with the approach, and that should have been resolved before it was merged.
