### ISSUE TITLE
The Concealable Baton is upside down.

### ISSUE THREAD

**Issue by VoodooHillbilly** [glacier-modding/H3-Community-Patches#28]
47 has been using the Concealable Baton upside down this entire time:
- [ ] He grips the extended bonking end and hits them with the grippy handle.
- [ ] The Baton's inventory icons are both upside down relative to other melee items.
- [ ] The Freelancer safehouse displays it backwards relative to the other nearby items.

**Comment by NeetBux-Hash** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/81e65b83-298b-477c-84a6-d002aa28c0a6)
This has been fixed or never was an issue
We close this issue

**Comment by Ocean-Minnow** [comment]
Currently under debate in the Discord - reopening for now

**Comment by VoodooHillbilly** [comment]
Might as well close this. Everyone else seems fine with this hideous backwards-for-a-baton club.
