### ISSUE TITLE
Inverted Normals on the Head of Akane Akenawa

### ISSUE THREAD

**Issue by dribbleondo** [glacier-modding/H3-Community-Patches#43]
This needs exporting out, normals flipped, then reimported.
![image](https://github.com/glacier-modding/H3-Community-Patches/assets/9034161/97310950-9d96-40ac-a894-8c65b9790e8f)

Basically the same issue #19 has.

**Comment by JojjeE** [comment]
Might not even need to do that if it's like #19 where there's a good version in an earlier patch. In such a case can just extract the good version.

**Comment by dribbleondo** [comment]
That's....yeah, that's a good idea.

**Comment by dribbleondo** [comment]
Done
![screenshot 9555](https://github.com/glacier-modding/H3-Community-Patches/assets/9034161/1389d146-9e11-4399-9031-83deaff09227)

**Comment by JojjeE** [comment]
Fixed in PR #44
