### ISSUE TITLE
Error: SetPropertyValue in chunk29\mission_vanilla.entity.patch.json

### ISSUE THREAD

**Issue by VoodooHillbilly** [glacier-modding/H3-Community-Patches#52]
I'm getting an error when trying to deploy 0.18.0 or 0.19.0:

```
DEBUG	Deploy	Applying patch C:\Apps\SimpleModFramework\Mods\GlacierOrganisation.CommunityPatches\content\chunk29\mission_vanilla.entity.patch.json
```
```
Error: Failure applying patch to entity

Caused by:
    SetPropertyValue couldn't find expected property!
```
Full details: [Deploy.log](https://github.com/glacier-modding/H3-Community-Patches/files/14317127/Deploy.log)
SMF 2.33.7
Windows 10 (VirtualBox)

After deleting chunk29, SMF deploys all mods without errors.

**Comment by Ocean-Minnow** [comment]
I'm not getting this one myself, even with my full mod list.

Just to be sure, have you already deployed this mod on its own to make sure it's not a conflict?

**Comment by VoodooHillbilly** [comment]
Yeah, that's the first thing I tried along with deleting the cache folder. Still getting the same error.
