### ISSUE TITLE
Flash Phone and Explosive Phone aren't properly destroyed on detonation

### ISSUE THREAD

**Issue by Ocean-Minnow** [glacier-modding/H3-Community-Patches#61]
When either of these items (and possibly others) are detonated, they leave behind an invisible item that NPCs will try to pick up. The NPC will never successfully pick up the item, and will be stuck in a loop forever. ~~In the case of the Goldbrick snail, it also plays the music forever.~~

This was previously an issue with the emetic gas device when detonated from inside a briefcase (which was fixed by IO)

**Comment by VoodooHillbilly** [comment]
The Explosive Phone has the same bug.

**Comment by Ocean-Minnow** [comment]
I've also confirmed that they did fix the snail since I last tested it. I hadn't noticed yet. I guess I was a bit... *slow*

**Comment by Cybore8** [comment]
I tried fixing this issue to no avail. Disableaiperceptible should've done the trick but they can still see the item post detonation for some reason. Other things I tried resulting in them getting stuck on listening to the phone.
