### ISSUE TITLE
Incorrect localization for Anemone - Level 5

### ISSUE THREAD

**Issue by RDIL** [glacier-modding/H3-Community-Patches#64]
Ref https://github.com/thepeacockproject/Peacock/issues/403

**Comment by dribbleondo** [comment]
![image](https://github.com/glacier-modding/H3-Community-Patches/assets/9034161/1659db1d-e76c-4086-ba8d-3077088e129e)

Fixing presently.

**Comment by dribbleondo** [comment]
[The Great Big Localisation Revamp.zip](https://github.com/glacier-modding/H3-Community-Patches/files/14760674/The.Great.Big.Localisation.Revamp.zip)

Please apply this mod to see if this fixes the issue.

**Comment by Ocean-Minnow** [comment]
Fixed in #65, but wasn't linked to this issue. Closing now.
