### ISSUE TITLE
New Master/Pro cameras in Colorado don't record 47 properly

### ISSUE THREAD

**Issue by Ocean-Minnow** [glacier-modding/H3-Community-Patches#80]
In Colorado, Master mode (`difficulty_pro1_bull.brick`) adds new cameras around the map. They don't seem to be hooked up properly and will only give the guards a "live feed". They will be able to spot 47 if he is committing a crime in sight of them, but simply being recorded will not break Silent Assassin or require the recorder box to be destroyed.

I believe there was a patch fixing another camera like this at some point, checking IO's patch notes may give some insight into what causes this; I remember something about it not being connected to a recorder box.

**Comment by Ocean-Minnow** [comment]
"The camera that IO fixed was the one in Ambrose when you're walking into the cave towards the satellite thing from the beach-ish area with the two huts and the boat exit with the key under the brick." -Thrison on Discord

**Comment by Watchman3001** [comment]
Also applies to cameras added on Master difficulty Santa Fortuna

**Comment by Ocean-Minnow** [comment]
Fixed by #114

**Comment by dribbleondo** [comment]
This does not work in Colorado: 
![image](https://github.com/glacier-modding/H3-Community-Patches/assets/9034161/074aec0c-9115-4e0d-b7e2-5668b7170da6)
![screenshot_6884](https://github.com/glacier-modding/H3-Community-Patches/assets/9034161/7976cab6-bbe8-4a66-9368-349d0b0236a6)
![screenshot_6883](https://github.com/glacier-modding/H3-Community-Patches/assets/9034161/82313908-8b13-4a1c-bfbc-76d935b47f68)
